---
title: "ICPMS_data_analysis"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)

sample_sites <- unique(filter(ICPMS_tidy_example,site!="MB")$site)
metals_analyzed <- unique(ICPMS_tidy_example$metal)

ICPMS_cal <- NULL

for(unique_metal in metals_analyzed){
  cal <- ICPMS_tidy_example %>%
    filter(type == "Cal1"|type == "Cal2"|type == "Cal3") %>%
    filter(metal == unique_metal) %>%
    select(conc = concentration,signal = cps,rsd)
  
  w <- 1/(cal$signal*cal$rsd)^2
  model <- lm(cal$signal ~ cal$conc, weights = w)
  
  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]
  
  plot(cal$signal ~ cal$conc,
       xlab = paste("Concentration of ",unique_metal,"(ppb)"),
       ylab = "Counts per Second") + 
    abline(model,col="red") +
    title(paste("Calibration for",unique_metal))
  
  equation <- data_frame(metal=unique_metal,slope,slope_std,intercept,intercept_std)
  ICPMS_cal <- rbind(ICPMS_cal, equation)
}
view(ICPMS_cal)

remove(equation,cal,slope,slope_std,intercept,intercept_std)


```


```{r setup, include=TRUE}
sample_analysis <- function(unique_site) {
  concentration_data <- NULL
  for(unique_metal in metals_analyzed) {
    sample <- filter(ICPMS_tidy_example,metal == unique_metal, site == unique_site)
    data <- NULL 
    
    for(ID in sample$sample_key){
      sample_data <- filter(sample, sample_key == ID)
      cal <- filter(ICPMS_cal,metal == unique_metal)
      m <- cal$slope
      b <- cal$intercept
      y <- sample_data$cps
      
      b_e <- cal$intercept_std
      m_e <- cal$slope_std
      x <- (y-b)/m
      
      RSD <- sample_data$rsd
      CPS <- sample_data$cps
      
      #sample propagation
      e_yb <- sqrt((RSD)^2+(b_e^2))
      #error in y-b from the calibration
      yb <- CPS-b
      e_x <- x*sqrt((e_yb/yb)^2+(m_e/m)^2)
      #error in x from the calibration
      data <-rbind(data,data_frame(sample_key=ID,x,e_x))
      
      if(unique_site != "MB"){
        concentration_data <- data_frame(sample_key = sample_data$sample_key,
                                         analyst = sample_data$analyst,
                                         metal = unique_metal,
                                         site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
          rbind(concentration_data)
      }
    }
      if(unique_site=="MB"){
        x <- mean(data$x)
        e_x <- sd(data$x)
        concentration_data <- data_frame(metal = unique_metal, site=unique_site,conc_dil = x,conc_dil_error = e_x) %>%
          rbind(concentration_data)
      }
  }
  return(concentration_data)
}
```

```{r}
run_sites <- function(Function) {
  value <- NULL
  for(sites in sample_sites) {
    site_value <- Function(sites)
    value <- rbind(site_value,value)
  }
  return(value)
}
```

```{r}
MB <- sample_analysis("MB")
uncor_sample <- run_sites(sample_analysis)

MB
uncor_sample
```

```{r}
sample_data_mb <- NULL

for(unique_metal in metals_analyzed) {
  MB_metal <- filter(MB, metal==unique_metal)
  sample_metal <- filter(uncor_sample,metal==unique_metal)
  conc_dil_blanked <- sample_metal$conc_dil-MB_metal$conc_dil
  
  conc_dil_blanked_error <- sqrt((sample_metal$conc_dil_error)^2+(MB_metal$conc_dil_error)^2)
  
  sample_data_mb <- sample_metal %>%
    mutate(conc_dil_blanked,conc_dil_blanked_error)%>%
    rbind(sample_data_mb)
}
sample_data_mb
```
### Sample prep procedure

```{r}
#error prop
vol_e <- 1
mass_e <- 0.001
dil_1010_e <- sqrt(1^2+10^2)
dil_e <- sqrt((dil_1010_e/1010)^2+(1/10)^2)

sample_merge <-merge(ICPMS_tidy_example,sample_data_mb)%>%
  unique()%>%
  mutate(conc_blanked = conc_dil_blanked*(total_volume/1000)/(mass_of_soil/1000)*101,
         
         conc_blanked_error= conc_blanked*
           sqrt((conc_dil_blanked_error/conc_dil_blanked)^2+
                  (dil_e/101)^2+
                  (mass_e/mass_of_soil)^2+
                  (vol_e/total_volume)^2),
         conc_blanked= conc_dil*(total_volume/1000)/(mass_of_soil/1000)*101,
         conc_blanked_error= conc_blanked*
           sqrt((conc_dil_error/101)^2+
                  (mass_e/mass_of_soil)^2+
                  (vol_e/total_volume)^2))%>%
  select(-concentration,
         -type,
         -total_volume,
         -cps,
         -rsd,
         -conc_dil_blanked,
         -conc_dil_blanked_error, -conc_dil,
         -conc_dil_error)

ICP_statistics <- sample_merge %>%
  group_by(site, metal) %>%
  filter(site != "QC")  %>%
  summarize(mean_conc = mean(conc_blanked),
            sd_conc = sd(conc_blanked),
            n = n()) %>%
  mutate(se = qnorm(0.975)*sd_conc/sqrt(n),
         lower_ci = mean_conc - se,
         upper_ci = mean_conc + se, 
         mass_frac = mean_conc/1000) %>%
 select(-n,
         -se)
view(ICP_statistics)

qc <- sample_merge %>%
  group_by(metal) %>%
  filter(site == "QC")  %>%
  summarize(mean_conc = mean(conc_blanked),
            sd_conc = sd(conc_blanked),
            n = n()) %>%
  mutate(se = qnorm(0.975)*sd_conc/sqrt(n),
         lower_ci = mean_conc - se,
         upper_ci = mean_conc + se, 
         mass_frac = mean_conc/1000) %>%
 select(-n,
         -se)
view(qc)


ICP_statistics %>%
ggplot(aes(x = metal, y = mass_frac, color =
site)) +
geom_point() +
geom_errorbar(aes(ymin=mean_conc - se,
ymax=mean_conc + se)) +
labs(x = "Metal",
     y = "Concentration of Metal",
     title = "Metal Concentrations by Site, ICP-MS")
```

