---
title: "metals_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(janitor)

ICPMS_Data <- read_csv("data/ICPMS_Data.csv", skip=1, na = "N/A")
view(ICPMS_Data)
Sample_Key <- read_csv("data/Sample_Key.csv",skip=0)

### tidying process for ICPMS_Data:
RSD_data <- ICPMS_Data %>%
select(Cr52 = `CPS RSD`,
      Cr53 = `CPS RSD_1`,
      As75 = `CPS RSD_2`,
      Cd111 = `CPS RSD_3`,
      Cd114 = `CPS RSD_4`,
      Pb208 = `CPS RSD_5`,
      Ge_RSD= `CPS RSD_7`,
      `Sample Key`) %>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "RSD")
 
ICPMS_tidy <- ICPMS_Data %>% 
  select(Cr52 = CPS,
         Cr53 = CPS_1,
         As75 = CPS_2,
         Cd111 = CPS_3,
         Cd114 = CPS_4,
         Pb208 = CPS_5,
         Ge72 = CPS_7,
         `Sample Key`) %>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "CPS") %>%
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,CPS=CPS/Ge72) %>%
  select(-Ge72)
view(ICPMS_tidy)

all(RSD_data$`Sample Key`==ICPMS_tidy$`Sample Key`,RSD_data$metal==ICPMS_tidy$metal) ### returns true if data matches

merged_ICPMS <- merge(ICPMS_tidy,Sample_Key)
view(merged_ICPMS)

write.csv(merged_ICPMS, file = "~/CHEM313_Miller/ICPMS_metals_miller/data/tidy_ICPMS.csv")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Tidying process for Cr AA_data:
AA_Data <- read_csv("data/AA_Data.csv",skip=4,na = "N/A")
view(AA_Data)

AA_merged <- merge(AA_Data,Sample_Key)
view(AA_merged) ### note to self: this should produce 65 observations if everything is retained properly

AA_checks <- filter(AA_Data, `Sample Key` == "Sample Blank"|`Sample Key` == "check10")
view(AA_std)

write.csv(AA_merged, file = "~/CHEM313_Miller/ICPMS_metals_miller/data/tidy_AA.csv")
write.csv(AA_checks, file = "~/CHEM313_Miller/ICPMS_metals_miller/data/checks_AA.csv")
 
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
